# Generated by Django 2.1 on 2018-08-15 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('add_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expenditure', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('receipt', models.TextField()),
                ('payment', models.BooleanField(default=False)),
                ('note', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
